repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: pnpm turbo lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cd apps/mainsite/api && cargo fmt --all -- --check'
        language: system
        files: ^apps/mainsite/api/.*\.rs$
        pass_filenames: false
        stages: [pre-commit]
